language: java
jdk: openjdk7

env:
  global:
  - TERM=dumb

  # Encrypted env variable SYNCANY_API_KEY for upload
  - secure: "V27h3/pPo7C5S/Mq866ZMss1n773aXt/tBW4L6HTeENvxwxZ2ORlaAcNGGr4aY4nsi/ttOkUkUOSYeWg26owD2/A7mh+naMjkBpTkFCB96DNlxn2569LAZNGyBYh818O7nIAiqk0sySIdUy+zqaacFjKPYLJKdSwyNOjUYymIps="
  
branches:
  only:
  - master
  - develop

notifications:
  email: false
  irc: chat.freenode.net#syncany

before_install:
  # Standard Stuff
  - sudo apt-get update
  - sudo apt-get install -y -q lftp
  - lftp -v
  - mkdir ~/.gradle 2> /dev/null || true
  - echo "org.gradle.daemon=true" > ~/.gradle/gradle.properties

  # Debian Packaging
  - sudo apt-get install -y -q dh-make devscripts debhelper bash-completion
  - gpg --version
  - debuild --version
  - perl -v

install:
  # Disable default travis behavior 'gradle assemble'
  - ./gradlew -v

script:
  # Be safe and clean!
  - ./gradlew clean

  # Build JAR and Debian DEB
  - ./gradlew pluginJar
  - ./gradlew pluginDebianDeb  

  # Upload JARs and DEBs
  - core/gradle/upload/upload-plugin.sh
